openapi: 3.0.0
info:
  title: Documentación de la API de Microsfot Store
  description: Documentación de la API de Store
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/JOELMACIAS/RawMarketplaces/1.0.0
  - url: https://storeedgefd.dsx.mp.microsoft.com/
paths:
  /v8.0/sdk/products:
    post:
      summary: Añadir producto
      description: Permite añadir un producto al carrito.
      parameters:
        - in: query
          name: market
          required: true
          schema:
            type: string
            example: US
          description: Código de mercado
        - in: query
          name: locale
          required: true
          schema:
            type: string
            example: en-US
          description: Localización
        - in: query
          name: deviceFamily
          required: true
          schema:
            type: string
            example: Windows.Desktop
          description: Familia de dispositivos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: "Se puede añadir más de un id de producto, separado por comas"
              properties:
                productIds:
                  type: string
                  example: "bwv5n56m5bvh"
      responses:
        '200':
          description: Producto añadido correctamente
          
          
  /v9.0/manifestSearch:
    post:
      summary: Búsqueda por parametro
      description: Permite buscar paremtoris en la tienda.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Query:
                  type: object
                  properties:
                    KeyWord:
                      type: string
                      example: "{{SEARCH_QUERY}}"
                      description: Palabra clave para la búsqueda
                    MatchType:
                      type: string
                      example: "{{Substring}}"
                      description: Tipo de coincidencia para la búsqueda
      responses:
        '200':
          description: Búsqueda exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManifestSearchResponse'
        '400':
          description: Solicitud incorrecta
components:
  schemas:
    ManifestSearchResponse:
      type: object
      properties:
        $type:
          type: string
          example: Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchResponse, StoreEdgeFD
        Data:
          type: array
          items:
            $ref: '#/components/schemas/ManifestSearchData'
    ManifestSearchData:
      type: object
      properties:
        $type:
          type: string
          example: Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchData, StoreEdgeFD
        PackageIdentifier:
          type: string
          example: 9WZDNCRFHVN5
        PackageName:
          type: string
          example: Windows Calculator
        Publisher:
          type: string
          example: Microsoft Corporation
        Versions:
          type: array
          items:
            $ref: '#/components/schemas/ManifestSearchVersion'
    ManifestSearchVersion:
      type: object
      properties:
        $type:
          type: string
          example: Microsoft.Marketplace.Storefront.StoreEdgeFD.BusinessLogic.Response.ManifestSearch.ManifestSearchVersion, StoreEdgeFD
        PackageVersion:
          type: string
          example: Unknown
        PackageFamilyNames:
          type: array
          items:
            type: string
            example: Microsoft.WindowsCalculator_8wekyb3d8bbwe