# Generated by Django 4.2.14 on 2024-08-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('api_name', models.TextField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('marketplace', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategoryInProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('category', models.TextField()),
                ('marketplace', models.TextField()),
            ],
            options={
                'db_table': 'CategoryInProduct',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('marketplace', models.TextField()),
            ],
            options={
                'db_table': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('marketplace', models.TextField()),
            ],
            options={
                'db_table': 'Market',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Marketplace',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('identifier', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('creator', models.TextField()),
                ('marketplace', models.TextField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('keywords', models.TextField()),
                ('marketplace', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ProductKeyword',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringSoftwareMarketplaces.category')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringSoftwareMarketplaces.market')),
            ],
            options={
                'db_table': 'CategoryInMarket',
            },
        ),
    ]
